from enum import Enum

class OpCode(str, Enum):
    PLUS = '+'
    MINUS = '-'
    TIMES = '*'
    DIVIDE = '/'
    JUMP = 'jump'
    JUMPTOF = 'jumpF '
    JUMPTOT = 'jumpT'
    MEMALLOC = 'memalloc'
    GOSUB = 'gosub'
    RETURN = 'return'
    PRINT = 'print'
    PARAM = 'param'
    ENDFUNC = 'endfunc'
    END = 'end'
    ASSIGN = '='
    GT = '>'
    LT = '<'
    GTE = '>='
    LTE = '<='
    EQUALS = '=='
    NEQUALS = '!='
    AND = '&&'
    OR = '||'
    NOT = '!'
    VER = 'ver'
    INPUT = 'input',
    ERA = 'era'
    ERAI = 'erai'
    ERAF = 'eraf'
    ERAB = 'erab'
    ERAC = 'erac'
    DIM = 'dim'
    ADDR = 'addr'
    CONVOLUTIONS = '.^.'

class Type(str, Enum):
    INT = 'int'
    FLOAT = 'float'
    CHAR = 'char'
    BOOL = 'bool'
    VOID = 'void'
    STRING = 'string'
    ADDRESS = 'address'
    TINT = 'tint'
    TFLOAT = 'tfloat'
    TCHAR = 'tchar'
    TBOOL = 'tbool'


class Scope(str, Enum):
    GLOBAL = 'global'
    LOCAL = 'local'